### ISSUE TITLE
version 2.1.1 breaks unit tests

### ISSUE THREAD

**Issue by spearsandshields** [bpmn-io/diagram-js-direct-editing#27] opened 2023-12-21 17:23 UTC
### Describe the Bug
The recent changes made in package.json seems to be causing issues in our unit test. 
Previously (as in v2.0.0), there were no main/module attributes, so the unit test node server was able to resolve the /index.js with ease as it was the default path. 
Now, the path has been changed to lib/index.js via module attribute, while it works with esm/browser, this causes issues in unit test that depends on it. 

I was able to bypass the issue locally by adding 
"main": "lib/Diagram.js",
alongside the modules attribute. 

This might also be better resolved with exports attribute
see below resources for more details/examples:
https://bun.sh/docs/runtime/modules#importing-packages
https://stackoverflow.com/questions/68572936/what-is-the-difference-between-main-and-module-vs-exports-in-package-json

  

### Steps to Reproduce

1. create a simple project that uses this as a dependency, preferably with vite and vitest
2. try to run tests
3. now this happens

### Expected Behavior

The package should be compatible with mainstream front-end unit test frameworks, and the corresponding runtime

### Environment

N/A as not a environment specific issue

**Comment by nikku** [comment] 2023-12-22 07:41
@spearsandshields Thanks of approaching us.

If you look into the `main` file you see that it is actually an ES module, not a commonjs file. We could re-add a `main` entry, and I'm happy to take a contribution to do this. But it would be miss-leading. 

I don't have the background to judge how bun could consume it as a `cjs` file, but fails to do so as a module.

**Comment by nikku** [comment] 2023-12-22 07:43
How do you consume the library? Via a CJS file or ES module?

```
const editing = require('diagram-js-direct-editing');

import editing from 'diagram-js-direct-editing';
```

**Comment by spearsandshields** [comment] 2023-12-22 15:52
Thanks nikku, currently this is being used as a transitive dependency. 
The main package I rely on is dmn.js. Chain kind of looks like dmn-js => dmn-js-drd => diagram-js-direct-editing.

Now I think I understand your intention better. Since this is indeed a esm package. I believe it does not need the main entry. 
If i understand it correctly now, node has the capability to handle esm module since v 12.17.0 

However, in order to let node know this is pure ems, a type:"module" annotation might be necessary.  [see this gist for more info](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

[or here](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling)

Do you think this change would better align with your goal?

**Comment by nikku** [comment] 2023-12-22 16:01
@spearsandshields I'm not sure what `bun` uses under the hood. But if any major module bundler (rollup, vite, webpack) has issues with consuming the packages as a `module` (through the field), then we have to talk. Based on the documentation you shared I don't understand why `bun` would not pick up the `module` file.

To solve your immediate problem I guess we could simply re-add the `main` entry, and remove it in the next major version. But that removal will come, because it is a bug.

**Comment by nikku** [comment] 2023-12-22 16:01
If you share a code sandbox to reproduce your setup then we may look into this, too.

**Comment by spearsandshields** [comment] 2023-12-22 16:13
I am not only using bun. the bun link was just a reference to the node-compatible runtime doc , for "export" attributes in package.json. (this happens to the node run time as well) 
I just tried the `type: "module"` change, and that does not fix the issue either, perhaps due to higher level dependencies still being commonjs? In the mean time, it would be nice if you could add the main entry back. 

I will see if I can come up with a code sandbox repro in the main time. Thanks alot!

**Comment by spearsandshields** [comment] 2023-12-22 17:16
@nikku 
here is a repro
https://stackblitz.com/edit/vitejs-vite-apbvbz?file=README.md 

try run `vitest --environment jsdom` and you should be able to see the issue

**Comment by torge-hmn** [comment] 2024-01-08 09:29
We're experiencing the same unit test issues using _vite_ (5.0.11) and _vitest_ (1.1.3). We include it as a dependency transitively using _bpmn-js_ (16.3.1).

Are there any updates on this issue?

**Comment by nikku** [comment] 2024-01-08 09:52
We're going to look at this soon.

**Comment by torge-hmn** [comment] 2024-01-08 10:28
Thanks for your quick response 👍🏼

**Comment by nikku** [comment] 2024-01-08 12:02
Will be fixed by https://github.com/bpmn-io/diagram-js-direct-editing/pull/29.

It looks safe to simply restore what we removed with `v2.1.1`.

**Closed** 2024-01-12 09:51 UTC
Labels: bug, needs review
